version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.12.14-management
    container_name: rabbitmq-broker
    environment:
      RABBITMQ_ERLANG_COOKIE: ${AMQP_COOKIE}
      RABBITMQ_DEFAULT_USER: ${AMQP_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
    env_file:
      - .env
    networks:
      - med-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://rabbitmq:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  kong:
    image: kong:3.3.1-alpine
    container_name: kong-api-gateway
    volumes:
      - ./kong-config.yml:/tmp/kong-config.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /tmp/kong-config.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled
    restart: on-failure
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - med-net
    ports:
      # - 8000:8000 # disponivel para uso
      # - 8001:8001 # api do kong
      - 8444:8444
      - 8443:8443

  nginx:
    image: nginx
    container_name: nginx-server
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - med-net
    depends_on:
      - kong

  med_connect_db:
    image: postgres:16
    container_name: med_connect_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    env_file:
      - .env
    volumes:
      - med_connect_db:/data/postgres
    ports:
      - 5432:5432
    networks:
      - med-net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - med_connect_db
    networks:
      - med-net

  med_connect_api:
    build: .
    container_name: med-connect
    environment:
      - PORT=3000
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - med_connect_db
    restart: always
    links:
      - med_connect_db
      - rabbitmq
    volumes:
      - .:/usr/api
    networks:
      - med-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://med_connect_api:3001/auth/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  med-net:
    driver: bridge
    external: false
volumes:
  med_connect_db:
  kong_data: {}
