apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: med-connect
data:
  PORT: "3000"
  NODE_ENV: "production"
  DB_HOST: "${DB_IP}"
  DB_USERNAME: "${DB_USERNAME}"
  DB_PORT: "5432"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_NAME: "${DB_NAME}"
  DB_DIALECT: postgres
  DB_SYNC: "true"

  AMQP_USERNAME: admin
  AMQP_PASSWORD: admin
  AMQP_COOKIE: "TRIBUFUSTACK"
  AMQP_PORT: "5672"
  AMQP_HOST: broker-service

  JWT_KEY: "${TOKEN_SECRET}"
  BCRYPT_COST: "12"
  AUTH_URL: http://kong-service:8001
  CONSUMER: "med-connect"
