apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: dealmachine/med-connect:1
        workingDir: /usr/api
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: api-configmap
        livenessProbe:
          httpGet:
            path: /auth/health
            port: 3000
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /auth/health
            port: 3000
          periodSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /auth/health
            port: 3000
          periodSeconds: 5
          failureThreshold: 30
