apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-configmap
  namespace: med-connect
data:
  kong-config.yml: |
    _format_version: "1.1"
    services:
    - name: auth
      url: http://api-service:3000
      routes:
      - name: auth_get
        methods: [GET]
        paths:
        - /auth/health
        strip_path: false
      - name: auth_post
        methods: [POST]
        paths:
        - /auth/users/login
        - /auth/doctors/login
        - /auth/doctors
        - /auth/users
        strip_path: false
      plugins:
      - name: http-log
        config:
          http_endpoint: https://webhook.site/b07af8bf-56d3-4755-a55d-e85e23aece9a
          method: POST
    - name: med_connect
      url: http://api-service:3000
      routes:
      - name: doctors
        methods: [GET, PUT]
        paths:
        - /doctors
        - /doctors/(?<id>\d+)/register
        strip_path: false
      - name: appointments
        methods: [GET, POST, PUT]
        paths:
        - /appointments/doctors/(?<id>\d+)
        - /appointments/users/(?<id>\d+)
        - /appointments/request/users/(?<userId>\d+)
        - /appointments/(?<id>\d+)/response
        strip_path: false
      plugins:
      - name: request-transformer
        config:
          add:
            headers:
            - "Content-Type: application/json"
      - name: jwt
        enabled: true
        config:
          key_claim_name: kid
          claims_to_verify:
          - exp
    consumers:
    - username: med-connect
      jwt_secrets:
      - algorithm: HS256
        secret: ${TOKEN_SECRET}
