name: OWASP ZAP Scan

on: [workflow_dispatch]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start web application
      run: |
        docker compose up -d

    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        target: 'http://localhost/api/auth/health'   
        
    - name: Upload ZAP Scan Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report
        path: results/zap

    - name: Stop web application
      run: |
        docker compose down